### ISSUE TITLE
[ Bug ] Mineing with pickaxe?

### ISSUE THREAD

**Issue by Godwhitelight** [gXLg/libr-getter#10]
If you got a diamond pickaxe with eff 5 it will choose it over an axe.

**Comment by gXLg** [comment]
Uh, should not happend actually, but I will look into it

**Comment by 7coil** [comment]
Seems to prefer higher enchantments; dumping all other tools into a temporary chest seems to work fine.

Instead of automatically trying to infer the "best tool for the job", I recommend a change where...
1. A user holds the tool they want to use to break the blocks in their main hand
2. A user holds the plinths in their offhand
3. A user runs the command to begin

> _As a_ user
> _I want to_ be able to choose what tool I use to break lecterns with
> _So that_ I can choose the best tool for the job, instead of the software trying to choose for me

**Comment by gXLg** [comment]
I will add a possibility to pick between options, but this will not happen very soon - busy with my final exams right now

**Comment by gXLg** [comment]
The issue has been found - the fix will be implemented along other features in the next release

**Comment by gXLg** [comment]
Fixed in [v1.2.7](https://github.com/gXLg/libr-getter/releases/tag/v1.2.7)
